/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment1;

/**
 *
 * @author Daniel García
 */
public class QuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizForm
     */
    public QuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAnswers = new javax.swing.ButtonGroup();
        btnNextQuestion = new javax.swing.JButton();
        radAnswer1 = new javax.swing.JRadioButton();
        radAnswer2 = new javax.swing.JRadioButton();
        radAnswer3 = new javax.swing.JRadioButton();
        radAnswer4 = new javax.swing.JRadioButton();
        lblAnswer1 = new javax.swing.JLabel();
        lblAnswer2 = new javax.swing.JLabel();
        lblAnswer3 = new javax.swing.JLabel();
        lblAnswer4 = new javax.swing.JLabel();
        lblQuestionTitle = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        imgQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Climate quiz");
        getContentPane().setLayout(null);

        btnNextQuestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNextQuestion.setText("Next");
        getContentPane().add(btnNextQuestion);
        btnNextQuestion.setBounds(239, 501, 137, 39);

        btnGroupAnswers.add(radAnswer1);
        radAnswer1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radAnswer1.setText("Answer 1");
        getContentPane().add(radAnswer1);
        radAnswer1.setBounds(182, 410, 98, 22);

        btnGroupAnswers.add(radAnswer2);
        radAnswer2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radAnswer2.setText("Answer 2");
        getContentPane().add(radAnswer2);
        radAnswer2.setBounds(182, 450, 98, 22);

        btnGroupAnswers.add(radAnswer3);
        radAnswer3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radAnswer3.setText("Answer 3");
        getContentPane().add(radAnswer3);
        radAnswer3.setBounds(404, 410, 98, 22);

        btnGroupAnswers.add(radAnswer4);
        radAnswer4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        radAnswer4.setText("Answer 4");
        getContentPane().add(radAnswer4);
        radAnswer4.setBounds(404, 450, 98, 22);

        lblAnswer1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnswer1.setText("A.");
        getContentPane().add(lblAnswer1);
        lblAnswer1.setBounds(134, 410, 30, 17);

        lblAnswer2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnswer2.setText("B.");
        getContentPane().add(lblAnswer2);
        lblAnswer2.setBounds(134, 452, 30, 17);

        lblAnswer3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnswer3.setText("C.");
        getContentPane().add(lblAnswer3);
        lblAnswer3.setBounds(356, 412, 30, 17);

        lblAnswer4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnswer4.setText("D.");
        getContentPane().add(lblAnswer4);
        lblAnswer4.setBounds(356, 452, 30, 16);

        lblQuestionTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuestionTitle.setText("Question number");
        getContentPane().add(lblQuestionTitle);
        lblQuestionTitle.setBounds(134, 344, 139, 22);

        lblQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblQuestion.setText("Question");
        getContentPane().add(lblQuestion);
        lblQuestion.setBounds(291, 349, 293, 17);

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExit.setText("Return to menu");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(527, 580, 155, 39);

        imgQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment1/img/cat.jpg"))); // NOI18N
        getContentPane().add(imgQuestion);
        imgQuestion.setBounds(134, 31, 375, 301);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new QuizIntroGUI().setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupAnswers;
    private javax.swing.JButton btnNextQuestion;
    private javax.swing.JLabel imgQuestion;
    private javax.swing.JLabel lblAnswer1;
    private javax.swing.JLabel lblAnswer2;
    private javax.swing.JLabel lblAnswer3;
    private javax.swing.JLabel lblAnswer4;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestionTitle;
    private javax.swing.JRadioButton radAnswer1;
    private javax.swing.JRadioButton radAnswer2;
    private javax.swing.JRadioButton radAnswer3;
    private javax.swing.JRadioButton radAnswer4;
    // End of variables declaration//GEN-END:variables
}
