/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edward
 */
public class LoginGUI extends javax.swing.JFrame {
    private User currentUser;

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        verifyLoginBtn.addActionListener((java.awt.event.ActionEvent evt) -> {
            verifyLoginBtnActionPerformed(evt);
        });
        registerUserBtn.addActionListener((java.awt.event.ActionEvent evt) -> {
            registerUserBtnActionPerformed(evt);
        });
    }

    private void verifyLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String enteredUsername = usernameInput.getText();
        String enteredPassword = passwordInput.getText();

        List<User> userList = readUserDataFromCSV(); // populates userList ArrayList

        // check to see if typed username and password is in the userList
        boolean loginSuccessful = false;
        for (User user : userList) {
            if (enteredUsername.equals(user.getUserName()) && enteredPassword.equals(user.getUserPass())) { // successful

                currentUser = user;// store the details of current user

                if ("Admin".equals(user.getRole())) { // if the role is admin open the admin panel
                    AdminGUI adminGUI = new AdminGUI();
                    adminGUI.setVisible(true);
                    this.dispose();
                } else { // otherwise show main menu
                    MainMenuGUI mainMenu = new MainMenuGUI(currentUser);
                    mainMenu.setVisible(true);
                                        this.dispose();

                }
                loginSuccessful = true;
                break;
            }
        }

        if (!loginSuccessful) { // unsuccessful login
            JOptionPane.showMessageDialog(this, "Incorrect username or password", "Login Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // method to read csv file
    private List<User> readUserDataFromCSV() {
        List<User> userList = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(
                new FileReader("src/project/users.csv"))) {
            String line;
            br.readLine(); // ignore headings

            while ((line = br.readLine()) != null) {
                String[] userData = line.split(",");
                if (userData.length >= 8) {
                    try {
                        User user = new User(userData[0], userData[1], userData[2], userData[3],
                                Integer.parseInt(userData[4]), userData[5], userData[6],
                                Integer.parseInt(userData[7]));
                        userList.add(user);
                    } catch (NumberFormatException e) {
                        System.out.println("Error parsing line: " + line);
                        e.printStackTrace(); // catch error
                    }
                }
            }
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }

        return userList;
    }

    private void registerUserBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // registration form
        RegistrationGUI registrationForm = new RegistrationGUI();
        registrationForm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        loginFormLbl = new javax.swing.JLabel();
        verifyLoginBtn = new javax.swing.JButton();
        registerUserBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLbl.setText("Username:");

        passwordLbl.setText("Password:");

        loginFormLbl.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        loginFormLbl.setText("Login");

        verifyLoginBtn.setText("Login");
        verifyLoginBtn.setActionCommand("");

        registerUserBtn.setText("Register");
        registerUserBtn.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(293, 293, 293)
                                                .addComponent(loginFormLbl))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(usernameLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                98, Short.MAX_VALUE)
                                                        .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(registerUserBtn)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(verifyLoginBtn))
                                                        .addComponent(passwordInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usernameInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(280, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(loginFormLbl)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLbl)
                                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLbl)
                                        .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(verifyLoginBtn)
                                        .addComponent(registerUserBtn))
                                .addContainerGap(283, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginFormLbl;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton registerUserBtn;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JButton verifyLoginBtn;
    // End of variables declaration//GEN-END:variables
}
