/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Color;

/**
 *
 * @author edward
 */
public class MainMenuGUI extends javax.swing.JFrame {
    private static User currentUser;

    /**
     * Creates new form MainMenuGUI
     * 
     * @param user
     */
    public MainMenuGUI(User user) {
        initComponents();
        MainMenuGUI.currentUser = user;
        
        //Center form in screen
        setLocationRelativeTo(null);
        //Set color
        getContentPane().setBackground(Color.decode("#FF8282"));

        if ("Admin".equals(currentUser.getRole())) {
            adminBtn.setVisible(true); // if the role is admin show the admin panel button
        } else {
            adminBtn.setVisible(false);
        }
    }

    // welcome message
    public void welcomeMsg(User user) {
        MainMenuGUI.currentUser = user;
        if (currentUser != null) {
            welcomeLbl.setText("Welcome, " + currentUser.getFirstName() + "!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quizMenuBtn = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        mainMenuFormLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quizMenuBtn.setText("Quiz Menu");
        quizMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizMenuBtnActionPerformed(evt);
            }
        });

        adminBtn.setText("Admin Panel");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        mainMenuFormLbl.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        mainMenuFormLbl.setText("Main Menu");

        welcomeLbl.setText("Welcome User!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(199, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(adminBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(quizMenuBtn,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 214,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(204, 204, 204))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(welcomeLbl)
                                                        .addGap(271, 271, 271))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(mainMenuFormLbl)
                                                        .addGap(194, 194, 194)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(mainMenuFormLbl)
                                .addGap(18, 18, 18)
                                .addComponent(welcomeLbl)
                                .addGap(26, 26, 26)
                                .addComponent(quizMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adminBtn)
                                .addContainerGap(207, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quizMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quizMenuBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        QuizIntroGUI quizInt = new QuizIntroGUI();
        //Pass current user to quiz
        if(MainMenuGUI.currentUser != null){
            quizInt.setUser(MainMenuGUI.currentUser);
        }
        quizInt.setVisible(true);
    }// GEN-LAST:event_quizMenuBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminBtnActionPerformed
        AdminGUI adminGUI = new AdminGUI();

        // Make the AdminGUI visible
        adminGUI.setVisible(true);
    }// GEN-LAST:event_adminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI(currentUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JLabel mainMenuFormLbl;
    private javax.swing.JButton quizMenuBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
