/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author edward
 */
public class RegistrationGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationGUI
     */
    public RegistrationGUI() {
        initComponents();
        termsAndConditionsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsAndConditionsCheckBoxActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationFormLbl = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        usernameRegInput = new javax.swing.JTextField();
        passwordRegInput = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        termsAndConditionsCheckBox = new javax.swing.JCheckBox();
        AgeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrationFormLbl.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        registrationFormLbl.setText("Registration Form");

        firstNameLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        firstNameLbl.setText("First Name:");

        lastNameLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lastNameLbl.setText("Last Name:");

        ageLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        ageLbl.setText("Age:");

        emailLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        emailLbl.setText("Email:");

        usernameLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        usernameLbl.setText("Username:");

        passwordLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        passwordLbl.setText("Password:");

        registerBtn.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        registerBtn.setText("Submit");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        termsAndConditionsCheckBox.setText("  I agree to the Terms and Conditions.    ");
        termsAndConditionsCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        termsAndConditionsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termsAndConditionsCheckBoxActionPerformed(evt);
            }
        });

        AgeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7",
                "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
                "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41",
                "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58",
                "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75",
                "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92",
                "93", "94", "95", "96", "97", "98", "99" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lastNameLbl)
                                        .addComponent(firstNameLbl)
                                        .addComponent(ageLbl)
                                        .addComponent(emailLbl)
                                        .addComponent(usernameLbl)
                                        .addComponent(passwordLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(termsAndConditionsCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(emailInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameRegInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordRegInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addComponent(AgeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(62, 62, 62))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(205, Short.MAX_VALUE)
                                .addComponent(registrationFormLbl)
                                .addGap(202, 202, 202)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(registrationFormLbl)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameLbl)
                                        .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLbl)
                                        .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ageLbl)
                                        .addComponent(AgeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLbl)
                                        .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLbl)
                                        .addComponent(usernameRegInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLbl)
                                        .addComponent(passwordRegInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(termsAndConditionsCheckBox))
                                .addContainerGap(138, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termsAndConditionsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_termsAndConditionsCheckBoxActionPerformed
        if (termsAndConditionsCheckBox.isSelected()) {
            registerBtn.setEnabled(true);
        } else {
            registerBtn.setEnabled(false);
        }
    }// GEN-LAST:event_termsAndConditionsCheckBoxActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_registerBtnActionPerformed
        // gets the information entered from the new user
        String firstName = firstNameInput.getText();
        String lastName = lastNameInput.getText();
        int age = Integer.parseInt((String) AgeComboBox.getSelectedItem());
        String email = emailInput.getText();
        String userName = usernameRegInput.getText();
        String userPass = passwordRegInput.getText();

        // checks if the terms and conditions are accepted
        if (!termsAndConditionsCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please accept the Terms and Conditions", "Registration Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        AppUser newUser = new AppUser(email, userName, userPass, "User", AppUser.getNextUserID(), firstName, lastName,
                age); // creates a new AppUser Object
        newUser.register(); // calls the register function from the AppUser class
        JOptionPane.showMessageDialog(this, "Registration successful", "Success", JOptionPane.INFORMATION_MESSAGE);

        this.dispose(); // closes the registration form
    }// GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgeComboBox;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordRegInput;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registrationFormLbl;
    private javax.swing.JCheckBox termsAndConditionsCheckBox;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameRegInput;
    // End of variables declaration//GEN-END:variables
}
